datasets:
  coco_advqa:
    # data_dir: ${env.data_dir}/datasets
    data_type: images # [images|videos|features]

    build_info:
      # Be careful not to append minus sign (-) before split to avoid itemizing
      annotations:
        val:
          url:
              - https://storage.googleapis.com/frames-vqa/datasets_files/advqa/combined_data.json
              - https://storage.googleapis.com/frames-vqa/datasets_files/vqav2/answer_list.json
              - https://storage.googleapis.com/frames-vqa/datasets_files/advqa/v1_OpenEnded_mscoco_val2017_advqa_questions.json
              - https://storage.googleapis.com/frames-vqa/datasets_files/advqa/v1_mscoco_val2017_advqa_annotations_new.json
          storage:
              - datasets_files/advqa/combined_data.json
              - datasets_files/vqav2/answer_list.json
              - datasets_files/advqa/v1_OpenEnded_mscoco_val2017_advqa_questions.json
              - datasets_files/advqa/v1_mscoco_val2017_advqa_annotations_new.json
        test:
          url:
              - https://storage.googleapis.com/frames-vqa/datasets_files/advqa/combined_data.json
              - https://storage.googleapis.com/frames-vqa/datasets_files/vqav2/answer_list.json
              - https://storage.googleapis.com/frames-vqa/datasets_files/advqa/v1_OpenEnded_mscoco_val2017_advqa_questions.json
              - https://storage.googleapis.com/frames-vqa/datasets_files/advqa/v1_mscoco_val2017_advqa_annotations_new.json
          storage:
              - datasets_files/advqa/combined_data.json
              - datasets_files/vqav2/answer_list.json
              - datasets_files/advqa/v1_OpenEnded_mscoco_val2017_advqa_questions.json
              - datasets_files/advqa/v1_mscoco_val2017_advqa_annotations_new.json
      images:
          storage: images/coco/