datasets:
  blink_visual_correspondance:
    data_type: images

    build_info:
      annotations:
        train:
          url: []
          storage: []
        val:
          url: []
          storage: []
        test:
          url: []
          storage: []
      images:
        storage: 'Visual_Correspondence'