datasets:
  blink_multiview_reasoning:
    data_type: images

    build_info:
      annotations:
        train:
          url: []
          storage: []
        val:
          url: []
          storage: []
        test:
          url: []
          storage: []
      images:
        storage: 'Multi-view_Reasoning'