datasets:
  blink_spatial_relation:
    data_type: images

    build_info:
      annotations:
        train:
          url: []
          storage: []
        val:
          url: []
          storage: []
        test:
          url: []
          storage: []
      images:
        storage: 'Spatial_Relation'