datasets:
  coco_vqa_raw:
    # data_dir: ${env.data_dir}/datasets
    data_type: images # [images|videos|features]

    build_info:
      # Be careful not to append minus sign (-) before split to avoid itemizing
      annotations:
        train:
          url:
              - https://storage.googleapis.com/frames-vqa/datasets_files/vqav2/vqa_train.json
              - https://storage.googleapis.com/frames-vqa/datasets_files/vqav2/vqa_val.json
          storage:
              - datasets_files/vqav2/vqa_train.json
              - datasets_files/vqav2/vqa_val.json
        val:
          url:
              # TODO make this order insensitive
              - https://storage.googleapis.com/frames-vqa/datasets_files/vqav2/vqa_val_eval.json
              - https://storage.googleapis.com/frames-vqa/datasets_files/vqav2/answer_list.json
              - https://storage.googleapis.com/frames-vqa/datasets_files/vqav2/v2_OpenEnded_mscoco_val2014_questions.json
              - https://storage.googleapis.com/frames-vqa/datasets_files/vqav2/v2_mscoco_val2014_annotations.json
          storage:
              - datasets_files/vqav2/vqa_val_eval.json
              - datasets_files/vqav2/answer_list.json
              - datasets_files/vqav2/v2_OpenEnded_mscoco_val2014_questions.json
              - datasets_files/vqav2/v2_mscoco_val2014_annotations.json
        test: 
          url:
              - https://storage.googleapis.com/frames-vqa/datasets_files/vqav2/vqa_test.json
              - https://storage.googleapis.com/frames-vqa/datasets_files/vqav2/answer_list.json
          storage:
              - datasets_files/vqav2/vqa_test.json
              - datasets_files/vqav2/answer_list.json
      images:
          storage: images/coco/