datasets:
  coco_okvqa:
    # data_dir: ${env.data_dir}/datasets
    data_type: images # [images|videos|features]

    build_info:
      # Be careful not to append minus sign (-) before split to avoid itemizing
      annotations:
        val:
          url:
              - https://storage.googleapis.com/frames-vqa/datasets_files/ok-vqa/combined_data.json
              - https://storage.googleapis.com/frames-vqa/datasets_files/vqav2/answer_list.json
              - https://storage.googleapis.com/frames-vqa/datasets_files/ok-vqa/OpenEnded_mscoco_val2014_questions.json
              - https://storage.googleapis.com/frames-vqa/datasets_files/ok-vqa/mscoco_val2014_annotations.json
          storage:
              - datasets_files/ok-vqa/combined_data.json
              - datasets_files/vqav2/answer_list.json
              - datasets_files/ok-vqa/OpenEnded_mscoco_val2014_questions.json
              - datasets_files/ok-vqa/mscoco_val2014_annotations.json
        test:
          url:
              - https://storage.googleapis.com/frames-vqa/datasets_files/ok-vqa/combined_data.json
              - https://storage.googleapis.com/frames-vqa/datasets_files/vqav2/answer_list.json
              - https://storage.googleapis.com/frames-vqa/datasets_files/ok-vqa/OpenEnded_mscoco_val2014_questions.json
              - https://storage.googleapis.com/frames-vqa/datasets_files/ok-vqa/mscoco_val2014_annotations.json
          storage:
              - datasets_files/ok-vqa/combined_data.json
              - datasets_files/vqav2/answer_list.json
              - datasets_files/ok-vqa/OpenEnded_mscoco_val2014_questions.json
              - datasets_files/ok-vqa/mscoco_val2014_annotations.json
      images:
          storage: images/coco/