datasets:
  vizwiz:
    # data_dir: ${env.data_dir}/datasets
    data_type: images # [images|videos|features]

    build_info:
      # Be careful not to append minus sign (-) before split to avoid itemizing
      annotations:
        val:
          url:
              - https://storage.googleapis.com/frames-vqa/datasets_files/vizwiz/combined_data.json
              - https://storage.googleapis.com/frames-vqa/datasets_files/vqav2/answer_list.json
              - https://storage.googleapis.com/frames-vqa/datasets_files/vizwiz/question.json
              - https://storage.googleapis.com/frames-vqa/datasets_files/vizwiz/annotation.json
          storage:
              - datasets_files/vizwiz/combined_data.json
              - datasets_files/vqav2/answer_list.json
              - datasets_files/vizwiz/question.json
              - datasets_files/vizwiz/annotation.json
        test:
          url:
              - https://storage.googleapis.com/frames-vqa/datasets_files/vizwiz/combined_data.json
              - https://storage.googleapis.com/frames-vqa/datasets_files/vqav2/answer_list.json
              - https://storage.googleapis.com/frames-vqa/datasets_files/vizwiz/question.json
              - https://storage.googleapis.com/frames-vqa/datasets_files/vizwiz/annotation.json
          storage:
              - datasets_files/vizwiz/combined_data.json
              - datasets_files/vqav2/answer_list.json
              - datasets_files/vizwiz/question.json
              - datasets_files/vizwiz/annotation.json
      images:
          storage: images/vizwiz/