datasets:
  coco_vqa_ce:
    # data_dir: ${env.data_dir}/datasets
    data_type: images # [images|videos|features]

    build_info:
      # Be careful not to append minus sign (-) before split to avoid itemizing
      annotations:
        val:
          url:
              - https://storage.googleapis.com/frames-vqa/datasets_files/vqa_ce/combined_data_subset.json
              - https://storage.googleapis.com/frames-vqa/datasets_files/vqav2/answer_list.json
              - https://storage.googleapis.com/frames-vqa/datasets_files/vqa_ce/question_subset.json
              - https://storage.googleapis.com/frames-vqa/datasets_files/vqa_ce/annotation_subset.json
          storage:
              - datasets_files/vqa_ce/combined_data_subset.json
              - datasets_files/vqav2/answer_list.json
              - datasets_files/vqa_ce/question_subset.json
              - datasets_files/vqa_ce/annotation_subset.json
        test:
          url:
              - https://storage.googleapis.com/frames-vqa/datasets_files/vqa_ce/combined_data_subset.json
              - https://storage.googleapis.com/frames-vqa/datasets_files/vqav2/answer_list.json
              - https://storage.googleapis.com/frames-vqa/datasets_files/vqa_ce/question_subset.json
              - https://storage.googleapis.com/frames-vqa/datasets_files/vqa_ce/annotation_subset.json
          storage:
              - datasets_files/vqa_ce/combined_data_subset.json
              - datasets_files/vqav2/answer_list.json
              - datasets_files/vqa_ce/question_subset.json
              - datasets_files/vqa_ce/annotation_subset.json
      images:
          storage: images/coco/