datasets:
  coco_vqa_cp:
    # data_dir: ${env.data_dir}/datasets
    data_type: images # [images|videos|features]

    build_info:
      # Be careful not to append minus sign (-) before split to avoid itemizing
      annotations:
        train:
          url:
              - https://storage.googleapis.com/frames-vqa/datasets_files/vqa_cp/vqacp_v2_train_questions.json
              - https://storage.googleapis.com/frames-vqa/datasets_files/vqa_cp/vqacp_v2_train_annotations.json
          storage:
              - datasets_files/vqa_cp/vqacp_v2_train_questions.json
              - datasets_files/vqa_cp/vqacp_v2_train_annotations.json
        val:  # == test
          url:
              - https://storage.googleapis.com/frames-vqa/datasets_files/vqa_cp/combined_data.json
              - https://storage.googleapis.com/frames-vqa/datasets_files/vqav2/answer_list.json
              - https://storage.googleapis.com/frames-vqa/datasets_files/vqa_cp/question_new.json
              - https://storage.googleapis.com/frames-vqa/datasets_files/vqa_cp/annotation_new.json
          storage:
              - datasets_files/vqa_cp/combined_data.json
              - datasets_files/vqav2/answer_list.json
              - datasets_files/vqa_cp/question_new.json
              - datasets_files/vqa_cp/annotation_new.json
        test:
          url:
              - https://storage.googleapis.com/frames-vqa/datasets_files/vqa_cp/combined_data.json
              - https://storage.googleapis.com/frames-vqa/datasets_files/vqav2/answer_list.json
              - https://storage.googleapis.com/frames-vqa/datasets_files/vqa_cp/question_new.json
              - https://storage.googleapis.com/frames-vqa/datasets_files/vqa_cp/annotation_new.json
          storage:
              - datasets_files/vqa_cp/combined_data.json
              - datasets_files/vqav2/answer_list.json
              - datasets_files/vqa_cp/question_new.json
              - datasets_files/vqa_cp/annotation_new.json
      images:
          storage: images/coco/