datasets:
  coco_vqa_rephrasings:
    # data_dir: ${env.data_dir}/datasets
    data_type: images # [images|videos|features]

    build_info:
      # Be careful not to append minus sign (-) before split to avoid itemizing
      annotations:
        val:
          url:
              - https://storage.googleapis.com/frames-vqa/datasets_files/vqa_rephrasings/combined_data.json
              - https://storage.googleapis.com/frames-vqa/datasets_files/vqav2/answer_list.json
              - https://storage.googleapis.com/frames-vqa/datasets_files/vqa_rephrasings/v2_OpenEnded_mscoco_valrep2014_humans_og_questions.json
              - https://storage.googleapis.com/frames-vqa/datasets_files/vqa_rephrasings/v2_mscoco_valrep2014_humans_og_annotations.json
          storage:
              - datasets_files/vqa_rephrasings/combined_data.json
              - datasets_files/vqav2/answer_list.json
              - datasets_files/vqa_rephrasings/v2_OpenEnded_mscoco_valrep2014_humans_og_questions.json
              - datasets_files/vqa_rephrasings/v2_mscoco_valrep2014_humans_og_annotations.json
        test:
          url:
              - https://storage.googleapis.com/frames-vqa/datasets_files/vqa_rephrasings/combined_data.json
              - https://storage.googleapis.com/frames-vqa/datasets_files/vqav2/answer_list.json
              - https://storage.googleapis.com/frames-vqa/datasets_files/vqa_rephrasings/v2_OpenEnded_mscoco_valrep2014_humans_og_questions.json
              - https://storage.googleapis.com/frames-vqa/datasets_files/vqa_rephrasings/v2_mscoco_valrep2014_humans_og_annotations.json
          storage:
              - datasets_files/vqa_rephrasings/combined_data.json
              - datasets_files/vqav2/answer_list.json
              - datasets_files/vqa_rephrasings/v2_OpenEnded_mscoco_valrep2014_humans_og_questions.json
              - datasets_files/vqa_rephrasings/v2_mscoco_valrep2014_humans_og_annotations.json
      images:
          storage: images/coco/

