datasets:
  gqa_ood:
    # data_dir: ${env.data_dir}/datasets
    data_type: images # [images|videos|features]

    build_info:
      # Be careful not to append minus sign (-) before split to avoid itemizing
      annotations:
        val:
          url:
              - https://storage.googleapis.com/frames-vqa/datasets_files/gqa-ood/ood_val_all.json
          storage:
              - datasets_files/gqa-ood/ood_val_all.json
        test:
          url:
              - https://storage.googleapis.com/frames-vqa/datasets_files/gqa-ood/ood_testdev_all.json
          storage:
              - datasets_files/gqa-ood/ood_testdev_all.json
      images:
          storage: images/gqa/
